export const GET_CURRENCY_LIST_ACT = 'GET_CURRENCY_LIST_ACT'

/** user */
export const LOGIN_USER_ACT = 'LOGIN_USER_ACT'
export const LOGOUT_USER_ACT = 'LOGOUT_USER_ACT'
export const REGISTER_USER_ACT = 'REGISTER_USER_ACT'
